import SwiftUI
import SwiftData

@available(iOS 17, *)
class FoodStore: ObservableObject{
    var smallFoods: [Food] = [
        Food(name: "Almonds", icon: "🌰", calories: 164, proteins: 6, fat: 14, carbohydrates: 6),
        Food(name: "Apple", icon: "🍎", calories: 95, proteins: 0.5, fat: 0.3, carbohydrates: 25),
        Food(name: "Avocado", icon: "🥑", calories: 160, proteins: 2, fat: 15, carbohydrates: 9),
        Food(name: "Bacon", icon: "🥓", calories: 42, proteins: 3, fat: 3.3, carbohydrates: 0.1),
        Food(name: "Banana", icon: "🍌", calories: 105, proteins: 1.3, fat: 0.3, carbohydrates: 27),
        Food(name: "Beef", icon: "🥩", calories: 250, proteins: 26, fat: 15, carbohydrates: 0),
        Food(name: "Bell Pepper", icon: "🌶", calories: 24, proteins: 1, fat: 0.2, carbohydrates: 6),
        Food(name: "Black Beans", icon: "🫘", calories: 132, proteins: 8.9, fat: 0.5, carbohydrates: 23.7),
        Food(name: "Blackberries", icon: "🍇", calories: 43, proteins: 1.4, fat: 0.5, carbohydrates: 9.6),
        Food(name: "Blueberries", icon: "🫐", calories: 84, proteins: 1.1, fat: 0.5, carbohydrates: 21.4),
        Food(name: "Bread", icon: "🍞", calories: 80, proteins: 3, fat: 1, carbohydrates: 15),
        Food(name: "Broccoli", icon: "🥦", calories: 55, proteins: 3.7, fat: 0.6, carbohydrates: 11.2),
        Food(name: "Brussels Sprouts", icon: "🥦", calories: 38, proteins: 3, fat: 0.3, carbohydrates: 8.1),
        Food(name: "Butter", icon: "🧈", calories: 102, proteins: 0.1, fat: 11.5, carbohydrates: 0),
        Food(name: "Cabbage", icon: "🥬", calories: 25, proteins: 1.3, fat: 0.1, carbohydrates: 5.8),
        Food(name: "Carrot", icon: "🥕", calories: 25, proteins: 0.6, fat: 0.1, carbohydrates: 6),
        Food(name: "Cauliflower", icon: "🥦", calories: 25, proteins: 2, fat: 0.3, carbohydrates: 4.9),
        Food(name: "Celery", icon: "🥬", calories: 16, proteins: 0.7, fat: 0.2, carbohydrates: 3),
        Food(name: "Cheese", icon: "🧀", calories: 113, proteins: 7, fat: 9, carbohydrates: 1),
        Food(name: "Chicken Breast", icon: "🍗", calories: 165, proteins: 31, fat: 3.6, carbohydrates: 0),
        Food(name: "Chickpeas", icon: "🫘", calories: 164, proteins: 8.9, fat: 2.6, carbohydrates: 27.4),
        Food(name: "Chili Pepper", icon: "🌶", calories: 40, proteins: 1.9, fat: 0.4, carbohydrates: 9.5),
        Food(name: "Cherries", icon: "🍒", calories: 50, proteins: 1, fat: 0.3, carbohydrates: 12),
        Food(name: "Chia Seeds", icon: "🌱", calories: 486, proteins: 16.5, fat: 30.7, carbohydrates: 42.1),
        Food(name: "Coconut", icon: "🥥", calories: 354, proteins: 3.3, fat: 33.5, carbohydrates: 15.2),
        Food(name: "Corn", icon: "🌽", calories: 86, proteins: 3.2, fat: 1.2, carbohydrates: 19),
        Food(name: "Cranberries", icon: "🍒", calories: 46, proteins: 0.4, fat: 0.1, carbohydrates: 12.2),
        Food(name: "Cucumber", icon: "🥒", calories: 16, proteins: 0.7, fat: 0.1, carbohydrates: 3.6),
        Food(name: "Dates", icon: "🌴", calories: 282, proteins: 2.5, fat: 0.4, carbohydrates: 75),
        Food(name: "Egg", icon: "🍳", calories: 68, proteins: 6, fat: 5, carbohydrates: 1),
        Food(name: "Eggplant", icon: "🍆", calories: 25, proteins: 1, fat: 0.2, carbohydrates: 5.9),
        Food(name: "Garlic", icon: "🧄", calories: 149, proteins: 6.4, fat: 0.5, carbohydrates: 33.1),
        Food(name: "Ginger", icon: "🌿", calories: 80, proteins: 1.8, fat: 0.8, carbohydrates: 17.8),
        Food(name: "Goji Berries", icon: "🍒", calories: 349, proteins: 14.3, fat: 0.4, carbohydrates: 77.1),
        Food(name: "Grapes", icon: "🍇", calories: 62, proteins: 0.6, fat: 0.3, carbohydrates: 16),
        Food(name: "Green Beans", icon: "🫘", calories: 31, proteins: 1.8, fat: 0.2, carbohydrates: 7),
        Food(name: "Green Peas", icon: "🍵", calories: 81, proteins: 5.4, fat: 0.4, carbohydrates: 14.5),
        Food(name: "Kale", icon: "🥬", calories: 49, proteins: 4.3, fat: 0.9, carbohydrates: 8.8),
        Food(name: "Kiwi", icon: "🥝", calories: 61, proteins: 1.1, fat: 0.5, carbohydrates: 14.7),
        Food(name: "Lemon", icon: "🍋", calories: 29, proteins: 1.1, fat: 0.3, carbohydrates: 9.3),
        Food(name: "Lettuce", icon: "🥬", calories: 15, proteins: 1, fat: 0.2, carbohydrates: 2.9),
        Food(name: "Lime", icon: "🍋", calories: 30, proteins: 0.7, fat: 0.2, carbohydrates: 10.5),
        Food(name: "Milk", icon: "🥛", calories: 103, proteins: 8, fat: 2.4, carbohydrates: 12),
        Food(name: "Mushroom", icon: "🍄", calories: 22, proteins: 3.1, fat: 0.3, carbohydrates: 3.3),
        Food(name: "Onion", icon: "🧅", calories: 40, proteins: 1.1, fat: 0.1, carbohydrates: 9.3),
        Food(name: "Orange", icon: "🍊", calories: 62, proteins: 1.2, fat: 0.2, carbohydrates: 15.4),
        Food(name: "Papaya", icon: "🍈", calories: 43, proteins: 0.5, fat: 0.3, carbohydrates: 10.8),
        Food(name: "Pasta", icon: "🍝", calories: 221, proteins: 7, fat: 1.3, carbohydrates: 43.5),
        Food(name: "Peach", icon: "🍑", calories: 59, proteins: 1, fat: 0.4, carbohydrates: 15),
        Food(name: "Peanut Butter", icon: "🥜", calories: 188, proteins: 8, fat: 16, carbohydrates: 6),
        Food(name: "Peas", icon: "🍵", calories: 81, proteins: 5.4, fat: 0.4, carbohydrates: 14.5),
        Food(name: "Pineapple", icon: "🍍", calories: 50, proteins: 0.5, fat: 0.1, carbohydrates: 13),
        Food(name: "Potato", icon: "🥔", calories: 77, proteins: 2, fat: 0.1, carbohydrates: 17),
        Food(name: "Pumpkin", icon: "🎃", calories: 26, proteins: 1, fat: 0.1, carbohydrates: 6.5),
        Food(name: "Quinoa", icon: "🌾", calories: 120, proteins: 4.1, fat: 1.9, carbohydrates: 21.3),
        Food(name: "Radish", icon: "🌶", calories: 16, proteins: 0.7, fat: 0.1, carbohydrates: 3.4),
        Food(name: "Raspberries", icon: "🍇", calories: 52, proteins: 1.2, fat: 0.7, carbohydrates: 11.9),
        Food(name: "Red Bell Pepper", icon: "🌶", calories: 31, proteins: 1, fat: 0.3, carbohydrates: 6),
        Food(name: "Rice", icon: "🍚", calories: 206, proteins: 4.3, fat: 0.4, carbohydrates: 44.8),
        Food(name: "Salmon", icon: "🐟", calories: 200, proteins: 22, fat: 12, carbohydrates: 0),
        Food(name: "Sausage", icon: "🌭", calories: 250, proteins: 14, fat: 22, carbohydrates: 2),
        Food(name: "Sesame Seeds", icon: "🌱", calories: 573, proteins: 17, fat: 49.7, carbohydrates: 23.5),
        Food(name: "Shrimp", icon: "🍤", calories: 99, proteins: 24, fat: 0.3, carbohydrates: 0),
        Food(name: "Slice of Bread", icon: "🍞", calories: 80, proteins: 3, fat: 1, carbohydrates: 15),
        Food(name: "Soybeans", icon: "🌱", calories: 446, proteins: 36.5, fat: 19.9, carbohydrates: 30.2),
        Food(name: "Spinach", icon: "🍃", calories: 7, proteins: 0.9, fat: 0.1, carbohydrates: 1.1),
        Food(name: "Steak", icon: "🥩", calories: 242, proteins: 26, fat: 15, carbohydrates: 0),
        Food(name: "Strawberries", icon: "🍓", calories: 49, proteins: 1, fat: 0.5, carbohydrates: 11.7),
        Food(name: "Sunflower Seeds", icon: "🌻", calories: 584, proteins: 20.8, fat: 51.5, carbohydrates: 20),
        Food(name: "Sweet Potato", icon: "🍠", calories: 112, proteins: 2, fat: 0.1, carbohydrates: 26),
        Food(name: "Tangerine", icon: "🍊", calories: 53, proteins: 0.8, fat: 0.3, carbohydrates: 13.3),
        Food(name: "Tofu", icon: "🍲", calories: 76, proteins: 8, fat: 4.8, carbohydrates: 1.9),
        Food(name: "Tomato", icon: "🍅", calories: 22, proteins: 1, fat: 0.2, carbohydrates: 4.8),
        Food(name: "Turkey", icon: "🦃", calories: 135, proteins: 24, fat: 3, carbohydrates: 0),
        Food(name: "Walnuts", icon: "🌰", calories: 185, proteins: 4.3, fat: 18.5, carbohydrates: 3.9),
        Food(name: "Watermelon", icon: "🍉", calories: 30, proteins: 0.6, fat: 0.2, carbohydrates: 7.6),
        Food(name: "Wheat Bread", icon: "🍞", calories: 69, proteins: 3.6, fat: 1.1, carbohydrates: 11.6),
        Food(name: "White Rice", icon: "🍚", calories: 130, proteins: 2.4, fat: 0.3, carbohydrates: 28.7),
        Food(name: "Yogurt", icon: "🥛", calories: 59, proteins: 10, fat: 0.4, carbohydrates: 3.6),
        Food(name: "Yellow Bell Pepper", icon: "🌶", calories: 27, proteins: 1, fat: 0.2, carbohydrates: 6.3),
        Food(name: "Zucchini", icon: "🥒", calories: 33, proteins: 2.4, fat: 0.4, carbohydrates: 6.1),
    ]
}